name: Build and push Docker images
on:
  release:
    types: [published]

env:
  TZ: Asia/Shanghai 

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Download and Unzip Upstream Source Code
        run: |
          curl -OL https://github.com/lsky-org/lsky-pro/archive/refs/tags/2.1.zip
          unzip *.zip
          mv ./lsky-pro-master/* ./
          mv ./lsky-pro-master/.env.example ./
          rm -rf master.zip lsky-pro-master

      - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
        with:
          php-version: '8.1'
        
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"
      
      - name: Install Dependencies
        run: composer install

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      
      - name: Build and push
        run: |
          docker build -t liuzzzz/lskypro:2.1 .
          docker push liuzzzz/lskypro:2.1
